### ISSUE TITLE
ospl.exe is missing (at least) in releases of v6.9

### ISSUE THREAD

**Issue by ronaldvanmanen** [ADLINK-IST/opensplice#105]
I'm trying to run OpenSplice in shared memory mode, but _ospl.exe_ seems to be missing from the bin folder. I'm currently using version _6.9.190705OSS-HDE-x86_64.win-vs2017_ (downloaded via https://github.com/ADLINK-IST/opensplice/releases), but I've also tried other versions including the latest release, _6.9.190925OSS-HDE-x86_64.win-vs2017_. From what I'm gathering all v6.9 releases are missing _ospl.exe_.

Is this intentional? I can't seem to find any documentation on this.

**Comment by ThijsSassen** [comment]
@ronaldvanmanen the OpenSource version of OpenSplice does not contain shared memory support. Our commercial version does support this.

**Comment by ronaldvanmanen** [comment]
@ThijsSassen Ok, that was the part I was missing apparently. Thanks!
