### ISSUE TITLE
No such file or directory "kernelModuleI.h" cross compile error for armv7l.linux-release. 

### ISSUE THREAD

**Issue by subhamdas88** [ADLINK-IST/opensplice#106]
**I am trying to cross compile opensplice(OSPL_V6_9_190925OSS_RELEASE) on Debian 8.11.1 (jessie) with armhf cross compiler for the armv7l.linux-release.

I am facing following error can somebody help on this issue?**

> /home/tec/Desktop/opensplice-master/src/kernel/include/v_kernel.h:29:27: fatal error: kernelModuleI.h: No such file or directory
 #include "kernelModuleI.h"
                           ^
compilation terminated.
/home/tec/Desktop/opensplice-master/setup/makefiles/rules.mak:187: recipe for target 'v_timedValue.o' failed
make[3]: *** [v_timedValue.o] Error 1
make[3]: Leaving directory '/home/tec/Desktop/opensplice-master/src/osplcore/bld/armv7l.linux-release'
makefile:6: recipe for target 'link' failed
make[2]: *** [link] Error 2
make[2]: Leaving directory '/home/tec/Desktop/opensplice-master/src/osplcore'
/home/tec/Desktop/opensplice-master/setup/makefiles/subsystem.mak:5: recipe for target 'osplcore.ss_link' failed
make[1]: *** [osplcore.ss_link] Error 2
make[1]: Leaving directory '/home/tec/Desktop/opensplice-master/src'
/home/tec/Desktop/opensplice-master/setup/makefiles/subsystem.mak:5: recipe for target 'src.ss_link' failed
make: *** [src.ss_link] Error 2

**Comment by ThijsSassen** [comment]
hi @subhamdas88 in order to compile the kernel you need the idlpp executable. Idlpp needs to be build for the host environment and with this the KernelModule.h can be generated.

**Comment by subhamdas88** [comment]
@ThijsSassen Thanks for the hint!
We are able to cross compile the source.
