### ISSUE TITLE
Random Corruption on Startup

### ISSUE THREAD

**Issue by fresh-ji** [ADLINK-IST/opensplice#107]
Dear whom it my concerned,
I am following the opensplice dds hello world example to test my application.
First i packaged my "messenger related thing" into DataTypes.dll, then i revised "DDSEntityManager.h" to support multiple topic, datawriter and datareader managements, at last i created serveral topics, datawriters and datareaders.
However, on the last process, the application corrupted at random time. It means:
1.the corruption occurs RANDOMLY, from my test about one in two the corruption occurs. But once the application starts normally, the following processes would goes well without any exceptions.
2.the corruption point occurs RANDOMLY, it could happen when any topic is being created, when any datawriter is being created, when any datareader is being created, when subscriber is being created, when publisher is being created. Once it happens, the console window shut down itself and left nothing.

My dds edition:PXXX-VortexOpenSplice-6.9.181018OSS-HDE-x86_64.win-vs2017-installer
My ide edition:visual studio 2013

**Comment by fresh-ji** [comment]
![捕获2](https://user-images.githubusercontent.com/25540984/69505897-20872f80-0f67-11ea-88c3-b13fd60a4844.PNG)
this is the normal situation, everything well

**Comment by fresh-ji** [comment]
![捕获1](https://user-images.githubusercontent.com/25540984/69505915-3d236780-0f67-11ea-8eeb-d8cb5558a46f.PNG)
![捕获3](https://user-images.githubusercontent.com/25540984/69505918-401e5800-0f67-11ea-8644-8e995117d23f.PNG)
![捕获4](https://user-images.githubusercontent.com/25540984/69505919-41e81b80-0f67-11ea-9258-b4e1b6ae6507.PNG)

Those are failed situation. The application stops at a random point, waiting 1 second , and corrupts.

**Comment by ThijsSassen** [comment]
@fresh-ji can you share the content of your ospl-info.log / ospl-error.log files? and the code of your example?

**Comment by fresh-ji** [comment]
This is the INFO when everything goes right:
[ospl-info-success.log](https://github.com/ADLINK-IST/opensplice/files/3885658/ospl-info-success.log)

This is the INFO when corruption happens:
[ospl-info-fail.log](https://github.com/ADLINK-IST/opensplice/files/3885659/ospl-info-fail.log)

The error-log do not generates every time, it means, somethings the program corrupts without error-log. In other times, the following one generates:
[ospl-error.log](https://github.com/ADLINK-IST/opensplice/files/3885675/ospl-error.log)

This is the primary invocation codes, the corruption could happens in these lines sometime:
![main](https://user-images.githubusercontent.com/25540984/69527107-8fd04400-0fa6-11ea-80a5-b3173f8cceb5.PNG)

At last is the "DDSEntityManager" your example provides, i revised it by adding a input parameter:
![ct](https://user-images.githubusercontent.com/25540984/69527175-b68e7a80-0fa6-11ea-93f9-ed7cdf494aaf.PNG)

Thanks for your concerning!

**Comment by ThijsSassen** [comment]
@fresh-ji the only indication i see in the logs is that some threads cannot make progress. Is there a high cpu load on your system or is your main loop spinning at 100% cpu? And from your code i can see you are using classic cpp API i would urge you to move to the isocpp2 API which is a much better fit for modern c++ programming.

**Comment by fresh-ji** [comment]
Thanks for your advices, i have found the isocpp2 examples and i will learn them carefully. I am just a fresh man of dds. I have a simple question:
I noticed that the examles you offered are alomost one-topic-only. In my situation, i want to register many topics and datawriters/datareaders. As a relsult, what framework should i take, just one thread to listen all or every datareader has its own thread. And which example should i refer to?
![捕获](https://user-images.githubusercontent.com/25540984/69542939-7ab7dd00-0fc7-11ea-9d21-e8bc35fe099c.PNG)
Thanks for your concerning.

**Comment by ThijsSassen** [comment]
@fresh-ji If your new to DDS then before you start building anything I suggest you start with a [dds tutorial](http://download.ist.adlinktech.com/docs/Vortex/pdfs/OpenSplice_DDSTutorial.pdf) and after this you can read through the [Getting started guide](http://download.ist.adlinktech.com/docs/Vortex/html/ospl/GettingStartedGuide/)
