### ISSUE TITLE
How to configure opensplice using MPC / mwc.pl

### ISSUE THREAD

**Issue by kjrusscher** [ADLINK-IST/opensplice#112]
I am using Yocto to build OS's for our platforms. How can I use `bin/mwc.pl` to configure the opensplice build system for different platforms?

**Comment by vivekpandey02** [comment]
Hi Kjrusscher,
For the Community Version i don't know how to configure it but Opensplice Commercial Edtion works on Yocto distribution.

**Comment by kjrusscher** [comment]
That is good to hear! What target and host did you use? We ran into problems when we tried to compile an armv7 target on a x86_64 host. In that case Yocto would configure Opensplice for the host, not for the target. As far as I can see, the only solution is to use mwc.pl to set the configure files to the target instead of the host.
