### ISSUE TITLE
OpenspliceDDS data read problem

### ISSUE THREAD

**Issue by ZTY-star** [ADLINK-IST/opensplice#113]
Will data readers in OpenspliceDDS conflict when reading data from the same key in different domains?

**Comment by hansvanthag** [comment]
A domain is not only a boundary for a/any reader, but also a boundary for the 'meaning' of information, so there's no guarantees whatsoever that reading 'the same' topic (w.r.t. name/structure/QoS) from multiple domains actually implies that these topic have the same meaning (perhaps one reads a temperature in Celcius and the other a temperature in fahrenheit) .. 
So with that being said, I'm (still) unsure how to interpret your question.. readers belong to a subscriber, which belongs to a participant, which belongs to a domain and which reads a topic (name/structure/qos) as defined in that domain .. so whether or not different readers reading data from different domains 'conflict' is not something that's captured in the specification .. I'd say that there's ample opportunity for these to conflict so your system-domain/design should be very careful/explicit in defining topics in multiple domains where its 'expected' that applications (with participants in multiple domains) can do something sensible with that data.

**Comment by ThijsSassen** [comment]
closing this as answered
