### ISSUE TITLE
NeoKylin  os support opensplice

### ISSUE THREAD

**Issue by Mr-jiayunfei** [ADLINK-IST/opensplice#116]
I can run hello-world example on windows os and ubuntu os,but i can not run it on Neokylin os.
i can publish data but cant not receive data in a computer on Neokylin os.
I want to konw does opensplice support Neokylin os?

**Comment by ThijsSassen** [comment]
Hi @Mr-jiayunfei we currently do not support Neokylin with Opensplice.
