### ISSUE TITLE
What does the WaitSet.dispatch() pattern look like for Python?

### ISSUE THREAD

**Issue by solarjoe** [ADLINK-IST/opensplice#120]
I could not figure out how `WaitSet.dispatch() ` could be used in Python?

Is there some workaround or something that I have missed to attach a callback function to a `WaitSet`?

**Comment by pgangula-adlink** [comment]
Hi Solarjoe,

WaitSet.dispatch() is explicit for ISOCPP API which basically invokes the handler associated with triggered condition as an alternative to find active conditions through iteration and execute the logic. But being a language with high abstraction Python should be able to provide such event handling mechanisms.

Best Regards,
Phani Gangula
Solutions Architect 
ADLINK Software and Solutions Group

**Comment by ThijsSassen** [comment]
closing this as answered
