### ISSUE TITLE
Typos in Doc?

### ISSUE THREAD

**Issue by solarjoe** [ADLINK-IST/opensplice#123]
1.)

https://github.com/ADLINK-IST/opensplice/blob/f40215c583c84e637229b77406e4060a6f39d043/src/api/dcps/python/code/dds.pyx#L970

```
def on_liveliness_changed(self, reader, status):
        :param writer: a handle to the reader
        :type writer: dds.ReaderWriter
```

Supposed to be:

        :param reader: a handle to the reader
        :type reader: dds.DataReader

?

2.) 

https://github.com/ADLINK-IST/opensplice/blob/f40215c583c84e637229b77406e4060a6f39d043/src/api/dcps/python/code/dds.pyx#L983

    def on_data_available(self, reader):

        :param writer: a handle to the reader
        :type writer: dds.DataReader

Supposed to be:

        :param **reader**: a handle to the reader
        :type writer: dds.DataReader

?

**Comment by vivekpandey02** [comment]
Dear Solarjoe,

Thanks for your valuable suggestions.

We consider your valuable suggestion, we will recompile our documents and correct it in future release.

**Comment by ThijsSassen** [comment]
solved with pr 124
