### ISSUE TITLE
HelloWorldData.h Not found in Examples directory

### ISSUE THREAD

**Issue by djacob91** [ADLINK-IST/opensplice#125]
I couldn't locate the HelloWorldData.h file required to compile the HelloWorld example program.
Where can i find it. It is not in the repository also. 

Regards
DJ

**Comment by ThijsSassen** [comment]
Hi @djacob91, you can generate this file with the idlpp preprocessor. Please see chapter 3 of the [Tutorial ](https://github.com/ADLINK-IST/opensplice/blob/master/docs/pdf/OpenSplice_Tutorial_C.pdf) that explains what idlpp is and how it can be used to generate your data model language files.

**Comment by djacob91** [comment]
Hi @ThijsSassen , Thank you.. that worked.
