### ISSUE TITLE
Helloworld Example Subscriber not receiving data - C, Cpp

### ISSUE THREAD

**Issue by djacob91** [ADLINK-IST/opensplice#127]
Hi,

I was trying to run the helloworld example in linux (RHEL8). Previously i was able to run similar examples on windows. I Have successfully build the example using the make file. However the subscriber is not receiving any data. The publisher successfully publishes the message though.

![image](https://user-images.githubusercontent.com/61504066/75603540-2b7cbf00-5a84-11ea-8480-d197506aacf2.png)

I have tried this for both the c and cpp , but the result is same. What could be the issue here?
Do i need to worry about any firewall settings or something of that sort?

Regards
DJ

**Comment by djacob91** [comment]
HI,

I just found out that if the firewall is turned off using the following command, the subscriber receives the message.
`sudo systemctl stop firewalld
`

![image](https://user-images.githubusercontent.com/61504066/75604813-9e406700-5a91-11ea-9c67-7427336cdcf7.png)

However i would like to enable the firewall back and still be able to use opensplice dds. How to do this? Add an exception for opensplice services in firewall?

**Comment by ThijsSassen** [comment]
Hi @djacob91 more information about port control when using DDSI as network service can be found in section 7.3.3 of the [deployment guide](https://github.com/ADLINK-IST/opensplice/blob/master/docs/pdf/OpenSplice_DeploymentGuide.pdf)

**Comment by djacob91** [comment]
Thank you @ThijsSassen 

Solved the issue by adding/opening a couple ports in the firewall.

Here are the commands used.

`# firewall-cmd --permanent --add-port 7400-7649/udp`

then restart firewall using

`# systemctl restart firewalld`

to verify the specified ports are open, use the following.

`# firewall-cmd --list-ports`

Hope this helps someone like me who is a newbie to all these.

Regards
DJ
