### ISSUE TITLE
copyIn / copyOut for Typedefs not exported in *SplDcps.h

### ISSUE THREAD

**Issue by mat-ct** [ADLINK-IST/opensplice#131]
Hi,

Is there a reason the copyIn and CopyOut methods are not exported for typedefs in the IDL when the compiler is run over them. 

They exist in the body just not exported in the header. 

This prevents me from having a base IDL in it's own library and then using the base IDL in another project.

IE:

```
// Library 'Base' built using base.idl below

module base
{
   typedef sequence <T_Char, 500> T_LongString;
   typedef T_LongString T_DescriptorType;
};
```

```
// Second library using the base.idl and linking to the Base library.

#include "base.idl"
module lib2
{
    struct Lib2Type
   {
      T_DescriptorType A_acousticGunshotDetectionSystemTypeName;
   };
};
```

**Comment by e-hndrks** [comment]
Hi James,

Good catch, thanks!!. I have reviewed your fix, and it seems OK to me. We will try to process pull request shortly.

Regards,
Erik Hendriks.
