### ISSUE TITLE
UDP make_socket failed error in QEMU

### ISSUE THREAD

**Issue by dodsonmg** [ADLINK-IST/opensplice#139]
I am attempting to run a simple ROS2 publisher and subscriber on FreeBSD in QEMU.

When I have either the publisher or subscriber running and then attempt to start the other one, I get the following error message:

`UDP make_socket failed for multicast port 7400`, which appears to arise from the following code snippet:

https://github.com/ADLINK-IST/opensplice/blob/6c48b0ed754c270107e50dd310e44ed28e8a529f/src/services/ddsi2e/core/ddsi_udp.c#L253-L258

I then get an error message specific to cyclone dds, which incorporates ddsi_udp:

`rmw_create_node: failed to create domain, error Error`, which appears to come from the following code snippet:

https://github.com/ros2/rmw_cyclonedds/blob/5c6b187fa948d206c1e8cb90fd319258819a32fc/rmw_cyclonedds_cpp/src/rmw_node.cpp#L677-L680

I would be grateful for some suggestions to narrow down the possible causes of this issue, since I'm not sure whether it's related to FreeBSD, QEMU, or my cross-compile toolchain.

I have been able to run a simple multicast communication test between the host and emulated environment, and `ifconfig` shows `MULTICAST` tags for both the `le0` and `lo0` interfaces in the emulated environment.

I'll also note that the exact same code base compiled for Ubuntu works just fine on the host machine.

**Comment by vivekpandey02** [comment]
Hi Dodsonmg,
It looks like cyclonedds error, Please log the error to cyclonedds forum url is given below:
https://github.com/ros2/rmw_cyclonedds

**Comment by dodsonmg** [comment]
Yes.  This was fixed by including the correct socket headers for `__FreeBSD__` (effectively, the same ones already included for `__APPLE__`.

I’ve tried to close this issue on a number of occasions, but for some reason GitHub won’t let me.  Feel free to close it yourself.

On 22 Apr 2020, at 13:04, vivekpandey02 <notifications@github.com<mailto:notifications@github.com>> wrote:



Hi Dodsonmg,
It looks like cyclonedds error, Please log the error to cyclonedds forum url is given below:
https://github.com/ros2/rmw_cyclonedds
