### ISSUE TITLE
Question about OSPL_HOST vs OSPL_TARGET

### ISSUE THREAD

**Issue by aohwang** [ADLINK-IST/opensplice#142]
I want to cross compile the OpenSplice on the X86_64 Linux for Arm Linux, and in this situation    is X86_64 Linux the OSPL_HOST? is Arm Linux the OSPL_TARGET? Thanks

**Comment by vivekpandey02** [comment]
Hi Aohwang,

Yes, Your thinking is right.  The OSPL_HOST is the machine on which you build your application. The OSPL_TARGET is the machine for which you generate the runtime. In your case you want to cross-compile OpenSplice application on a X86_64 Linux machine but the target is  Arm Linux then OSPL_HOST points to X86_64 Linux environment and OSPL_TARGET to the Arm Linux environment.

With best regards,
Vivek

**Comment by aohwang** [comment]
Thanks :)
