### ISSUE TITLE
Question about networking service

### ISSUE THREAD

**Issue by aohwang** [ADLINK-IST/opensplice#145]
Hi friends,
I notice that the networking service in directory src/services/networking is removed. Could you share the details why the networking service is removed? Thanks

**Comment by vivekpandey02** [comment]
Hi Aohwang,

Thank you for your query and curiosity about the Opensplice RTNetwoking service.

In the Community Edition we only supports DDSI and it extended version. RT-Networking service is part of our Commercial Edition only.  

Regarding your query about the removal of networking, it was never part of Community Edition.

For full capability of  DDS, please go with our commercial version.

With best regards,
Vivek

**Comment by hansvanthag** [comment]
I believe that in the initial community-edition (of many years ago), RTNetworking was indeed included, but as DDSI/RTPS has become THE interoperable networking-layer of DDS, that was included instead also as that assures interoperability with other DDS-vendors.
There are only a few/specific use-cases where the 'discovery-less' push-model of RTNetworking has (scalability-)advantage over DDSI (related to discovery-overhead) .. so typically you should be fine with DDSI. If you (think you) need RTNetworking, you should indeed go with the commercially-supported version as Vivek already indicated.

**Comment by aohwang** [comment]
Thanks your reply. :)
