### ISSUE TITLE
Communication problem between Python and C++

### ISSUE THREAD

**Issue by leonfg** [ADLINK-IST/opensplice#150]
Hello, I'm new to DDS. I implemented a topic finding program [InteropDDS](https://github.com/leonfg/InteropDDS) in python to try to communicate with [HelloWorld](https://github.com/ADLINK-IST/opensplice/tree/master/examples/dcps/HelloWorld) example. [findhello.py](https://github.com/leonfg/InteropDDS/blob/master/findhello.py) finds “HelloWorldData_Msg” topic and writes data to sub. When work with sacpp_helloworld_sub.exe, findhello does find the topic, but sacpp_helloworld_sub.exe cannot receive anything from findhello. And findhello works well with [subhello.py](https://github.com/leonfg/InteropDDS/blob/master/subhello.py), a sub program in python. 
How to fix the communication problem? Is it related to domain ID? There is not any method to set ID in python api.

Opensplice community 6.9.181127OSS.

**Comment by vivekpandey02** [comment]
Dear Mr. Fire God,

There is no communication problem in your case. sacpp subscriber is not getting the data because of **partition**.
In your findhello.py, you are publishing data in **default** partition but in HelloWorldDataSubscriber the partition name is **"HelloWorld Partition"** . Subscriber can only get the data from the same partition (or follow the wildcard). 
In DDS, Partitions provide a way of scoping information. This scoping mechanism can be used to organize topics into different coherent sets. You can get detailed information about partition from http://download.prismtech.com/docs/Vortex/html/ospl/DDSTutorial/topics-etc.html.

you can comment following lines of code in HelloWorldDataSubscriber.cpp to use default partition, your subscriber start getting the data.
.
sQos.partition.name.length(1);
 sQos.partition.name[0] = "HelloWorld Partition";


With best regards,
Vivek Pandey
Solutions Architect
ADLINK Technology

**Comment by leonfg** [comment]
It works, Thanks!
I have another question. The subhello.py can't receive data from HelloWorldDataSubscriber.cpp, nether commenting partition configuration in cpp nor setting same partition name with cpp in [xml](https://github.com/leonfg/InteropDDS/blob/master/DDS_DefaultQoS_All.xml).
> 
> 
> Dear Mr. Fire God,
> 
> There is no communication problem in your case. sacpp subscriber is not getting the data because of **partition**.
> In your findhello.py, you are publishing data in **default** partition but in HelloWorldDataSubscriber the partition name is **"HelloWorld Partition"** . Subscriber can only get the data from the same partition (or follow the wildcard).
> In DDS, Partitions provide a way of scoping information. This scoping mechanism can be used to organize topics into different coherent sets. You can get detailed information about partition from http://download.prismtech.com/docs/Vortex/html/ospl/DDSTutorial/topics-etc.html.
> 
> you can comment following lines of code in HelloWorldDataSubscriber.cpp to use default partition, your subscriber start getting the data.
> .
> sQos.partition.name.length(1);
> sQos.partition.name[0] = "HelloWorld Partition";
> 
> With best regards,
> Vivek Pandey
> Solutions Architect
> ADLINK Technology

**Comment by vivekpandey02** [comment]
Dear Fire God,
DDS uses a ‘request vs. offer’ QoS-matching approach,  in which a data reader matches a data writer if and only if the QoS it is requesting for the given topic does not exceed (i.e. it is no more stringent than) the QoS with which the data is produced by the data writer. DDS subscriptions are matched against the topic type and name, as well as against the QoS being offered and requested by data writers and readers.

You can get details from below link:
http://download.prismtech.com/docs/Vortex/html/ospl/DDSTutorial/qos.html

For your problem, you need to make below changes in your  DDS_DefaultQoS_All.xml. 
    <topic_qos>
          <topic_data>
               <value></value>
          </topic_data>
          <durability>
               <kind>TRANSIENT_DURABILITY_QOS</kind>
          </durability>
          <durability_service>
               <service_cleanup_delay>
                    <sec>0</sec>
                    <nanosec>0</nanosec>
               </service_cleanup_delay>
               <history_kind>KEEP_LAST_HISTORY_QOS</history_kind>
               <history_depth>1</history_depth>
               <max_samples>LENGTH_UNLIMITED</max_samples>
               <max_instances>LENGTH_UNLIMITED</max_instances>
               <max_samples_per_instance>LENGTH_UNLIMITED</max_samples_per_instance>
          </durability_service>
          <deadline>
               <period>
                    <sec>DURATION_INFINITE_SEC</sec>
                    <nanosec>DURATION_INFINITE_NSEC</nanosec>
               </period>
          </deadline>
          <latency_budget>
               <duration>
                    <sec>0</sec>
                    <nanosec>0</nanosec>
               </duration>
          </latency_budget>
          <liveliness>
               <kind>AUTOMATIC_LIVELINESS_QOS</kind>
               <lease_duration>
                    <sec>DURATION_INFINITE_SEC</sec>
                    <nanosec>DURATION_INFINITE_NSEC</nanosec>
               </lease_duration>
          </liveliness>
          <reliability>
               <kind>RELIABLE_RELIABILITY_QOS</kind>
               <max_blocking_time>
                    <sec>0</sec>
                    <nanosec>100000000</nanosec>
                    </max_blocking_time>
          </reliability>
          <destination_order>
               <kind>BY_RECEPTION_TIMESTAMP_DESTINATIONORDER_QOS</kind>
          </destination_order>
          <history>
               <kind>KEEP_LAST_HISTORY_QOS</kind>
               <depth>1</depth>
          </history>
          <resource_limits>
               <max_samples>LENGTH_UNLIMITED</max_samples>
               <max_instances>LENGTH_UNLIMITED</max_instances>
               <max_samples_per_instance>LENGTH_UNLIMITED</max_samples_per_instance>
          </resource_limits>
          <transport_priority>
               <value>0</value>
          </transport_priority>
          <lifespan>
               <duration>
                    <sec>DURATION_INFINITE_SEC</sec>
                    <nanosec>DURATION_INFINITE_NSEC</nanosec>
               </duration>
          </lifespan>
          <ownership>
               <kind>SHARED_OWNERSHIP_QOS</kind>
          </ownership>
     </topic_qos>

Comment pQos.partition code in HelloWorldDataPublisher.cpp
   /* pQos.partition.name.length(1);
    pQos.partition.name[0] = "HelloWorld Partition"; */
    /* Create the publisher. */

After above changes, Your subhello.py starts receiving  data from HelloWorldDataPublisher.


With best regards,
Vivek
