### ISSUE TITLE
Is it possible to use other transports?

### ISSUE THREAD

**Issue by aohwang** [ADLINK-IST/opensplice#153]
Hi friends,
For now OpenSplice supports UDP/TCP, is it possible to modify the source to support other transports? Are there any suggestions about how to do it?
Thanks

**Comment by vivekpandey02** [comment]
Dear Aoh Wang,

Thank you for your queries.

Our Vortex Opensplice DDS is compliant with OMG DDS specification and our implementation is  based on that only (with some extra features on top of specification).   Regarding your query about modification of the source to support other transports, I don't think we have any plan for this.

You can try our Eclipse Cyclon DDS. In Future, Some more transport protocols may be supported in it.   

We are keen to understand which transport protocol you are interested in to help studying the feasibility.

With best regards,
Vivek Pandey
Solution Architect
ADLINK Technology

**Comment by aohwang** [comment]
Hi vivekpandey02, thanks for your advices and I am sorry for the late reply. We are interested in making OpenSplice DDS to work with transports like RapidIO.
