### ISSUE TITLE
Embedibility: Can opensplice be combined on embedded devices?

### ISSUE THREAD

**Issue by vitiral** [ADLINK-IST/opensplice#16]
I am looking for an open source pub/sub protocol that can be compiled on embedded systems. I need the system to fit comfortably on devices with <32k of RAM and < 128k of flash.

Can opensplice do this currently? How difficult would you estimate it is to port it?

DDS looks like just about the perfect protocol for every level of communication. Thanks a lot!

**Comment by hansvanthag** [comment]
OpenSplice (and any OMG-DDS compliant) implementation will not fit in that footprint, but there's an interesting DDS-related technology that does fit and integrates fine with DDS.
See: https://github.com/atolab/zhe
