### ISSUE TITLE
bit.ly hyperlinks in documentation

### ISSUE THREAD

**Issue by DaveJarvis** [ADLINK-IST/opensplice#162]
Some companies block bit.ly for security reasons.

Consider updating the hyperlinks in the documentation to direct to the URL without going through any URL-shortener.

**Comment by vivekpandey02** [comment]
Dear Deve,

Thank you for your suggestion. We shall consider your suggestion in our future release.

With best regards,
Vivek Kumar Pandey
Solutions Architect
ADLINK Technology, SAT
