### ISSUE TITLE
Monitoring the data transmitted via OpenSplice

### ISSUE THREAD

**Issue by aratar-orome** [ADLINK-IST/opensplice#166]
Hello,

We are using OpenSplice Community Edition 5.4 in a shared memory architecture and want to easily monitor or have quick look on the messages that are transmitted via OpenSplice.

What I have seen so far is the OpenSplice Tuner. Is this possible with this tool? Or would you recommend another one?
https://github.com/ADLINK-IST/opensplice/blob/master/docs/pdf/OpenSplice_TunerGuide.pdf

Is the Tuner part of the Community Edition? I cannot find it.

Thanks in advance,

Andreas

**Comment by pgangula-adlink** [comment]
Hello Andreas,

Yes, Tuner and also Tester have the ability to monitor the DDS messages. 

https://github.com/ADLINK-IST/opensplice/blob/master/docs/pdf/OpenSplice_TesterUserGuide.pdf

Tuner allows you to look into your application and inspect / Tune DDS entities (Whitebox testing) whereas Tester can be used to test the behaviour of your system using scripts (Blackbox Testing). Both offer more than monitoring abilities. 

They are only part of our commercial offering! 

Best Regards
Phani

**Comment by pgangula-adlink** [comment]
For more information please contact IST_info@adlinktech.com

Best Regards
Phani
