### ISSUE TITLE
QNX igmp missing IP Router Alert option

### ISSUE THREAD

**Issue by trittsv** [ADLINK-IST/opensplice#177]
Hello,

on QNX opensplice does not send the IP Router Alert option.

Because of that it is not possible to send/recv messages when running on qnx with enabled igmp snooping.

Example:
```
IGMP Raw Data
Without Ip Alert
4500001ca619000001027388d070dfcdefff0001                1600f9feefff0001
With Ip Alert
46000020843500000102003fd070dff2efff0001    94040000    1600f9feefff0001
```
![grafik](https://user-images.githubusercontent.com/45872415/164389509-6e611356-8029-402e-ad7a-6d929f65ead0.png)

Is this a known problem or can anyone provide help?

**Comment by trittsv** [comment]
@eboasson, @k0ekk0ek do you have any idea where to search for this issue here?

May you could give me a little hint.
That would be awsome :)

**Comment by trittsv** [comment]
@ThijsSassen do you have a idea?

**Comment by eboasson** [comment]
Hi @trittsv I am afraid I have no idea. This sounds really QNX specific, and I have never used QNX myself (or maybe once, 20-odd years, and even if I’d remembered clearly, it would no longer be relevant …)
