### ISSUE TITLE
Build Instruction

### ISSUE THREAD

**Issue by kydos** [ADLINK-IST/opensplice#34]
It would be good if the README would explain how to build OpenSplice or at least point at a webpage that explains how to do so.

**Comment by kortstee** [comment]
You can find instructions here: http://www.prismtech.com/dds-community/building

**Comment by RobertPoth** [comment]
Currently missing on the build page is the dependency on the stdsoap2.c file which is expected to be found in the include directory of the soap install directory. Building OpenSplice without this file will fail.
The soap service which fails to build is actually not required and can be omitted from the build process by setting the build environment variable: INCLUDE_SERVICES_CMSOAP=no
If for any special reason you require the soapservice then you need to download the file from sourceforge.net/projects/gsoap2 and copy it into the (gsoaphome)/include directory.
Or for linux you can also remove the build dependency on this file in the (OpenSpliceHome)/src/services/cmsoap/makefile.mak file

**Comment by wsw2016** [comment]
My impression is, that the line 
stdsoap2.c : $(ESCAPED_GSOAPHOME)/include/stdsoap2.c
in src/services/cmsoap/makefile.mak is a simple mistake: who would expect a c-file in /usr/include? I renamed it to
stdsoap2.c : $(ESCAPED_GSOAPHOME)/include/stdsoap2.h
and it compiled to the end without any issues.

**Comment by mfeliu** [comment]
There is pull request #44  with @wsw2016 's fix

**Comment by michielb-prismtech** [comment]
removed the mandatory gSOAP dependency. If you want to enable the cmsoap service the source file is required in the GSOAPHOME/include directory, since this is somewhat unorthodox this dependency is no longer mandatory.
