### ISSUE TITLE
OpenSplice 6.7 Community not compatible with OpenDDS 3.11

### ISSUE THREAD

**Issue by matthewpang** [ADLINK-IST/opensplice#36]
OpenSplice is not compatible with OpenDDS 3.11
Companion issue on OpenDDS Github
https://github.com/objectcomputing/OpenDDS/issues/665

DDS Vendor Interoperability Chart
https://github.com/matthewpang/dds-interop

**Comment by mfeliu** [comment]
Could this [discussion](http://forums.opensplice.org/topic/2626-interop-issue/) help in order to solve it?
They propose a small correction that seemed to work.

**Comment by mitza-oci** [comment]
Before doing something more complex I'd suggest forcing OpenDDS to change its protocol version number, as I mentioned here: https://github.com/objectcomputing/OpenDDS/issues/665#issuecomment-309577642

**Comment by RomainNaour** [comment]
Hi,

As reported to https://github.com/objectcomputing/OpenDDS/issues/665#issuecomment-357946342
OpenSplice doesn't accept RTPS frames using the 2.2 protocol even if it's compatible.
I'm able to test with iShapes OpenDDS 3.12 and a modified version of OpenSplice 6.7.171127OSS.

Best regards,
Romain

**Comment by ernstvanveenendaal** [comment]
I've created a fix for this issue, OpenSplice indeed rejected RTPS messages with a minor version not equal to it's own version. It should accept all messages with the same major version and a minor version that is equal or higher that it's own. This is fixed in #45
