### ISSUE TITLE
Build Instruction Key FS Issue

### ISSUE THREAD

**Issue by cmanderino** [ADLINK-IST/opensplice#43]
I ran into continuous fails on make when the file would get to include subsystem.mak.

RESOLVED: make fails if your directory name is too long. I had to move it from where I had my git repo into my home directory to make it work.

**Comment by michielb-prismtech** [comment]
Good to read you were able to solve your problem, could you answer the following questions so we can check if we can resolve the issue in a future release?
- Which operating system did you use?
- How long was the path you used?
- Which error did you get?

**Comment by cmanderino** [comment]
Hi, thank you for the follow up:

- Ubuntu 16.04 LTS 64-bit
-  /home/***/******/***/**** is the directory path for the OSPLHOME containing the makefile.
- ~/setup/makefiles/subsystem.make: no such file or directory exists (I believe was the syntax, but it was the "I couldn't find such a thing by that name" error)

Including the "/" the directory path was 25 characters + "/makefile".

**Comment by michielb-prismtech** [comment]
that's shorter then the path we are using for our testing:
we use a path 10 levels deep with about 100 characters containing [A-Za-z0-9.-]
any special characters?

**Comment by cmanderino** [comment]
Interesting. I am not using any special characters, just upper-lowercase alphanumberic. It is, however, running in a VM in Oracle's Virtual Box. I don't know how that may work out with the handling of the virtual drive for the VM.

**Comment by michielb-prismtech** [comment]
Tested on a VM and cannot reproduce.

**Comment by cmanderino** [comment]
VM of Ubuntu 16(which is in VB on Ubuntu 16, itself), but it doesn't reproduce the problem?

Is there more information that could be helpful?

**Comment by cmanderino** [comment]
I re-produced the problem on this end.

Some added information:

makefile:32: /setup/makefiles/subsystem.mak: No such file or directory
make: *** No rule to make target '/setup/makefiles/subsystem.mak'.  Stop.
(USER)@(MACHINE):~/------/--------/----------/----------$ 

And if it helps:

$gcc --version:
gcc (Ubuntu 4.8.5-4ubuntu2) 4.8.5

This is also done without JAVA. I've attached the configure file:

[envs-x86_64.linux-release.txt](https://github.com/PrismTech/opensplice/files/1278313/envs-x86_64.linux-release.txt)

makefile:
[makefile.txt](https://github.com/PrismTech/opensplice/files/1278320/makefile.txt)

Do mind, I re-saved these files as .txt so that  I could upload them, here, but they are ".sh" and "makefile", repsectively.

**PrismTech OpenSpliceCE
**Apache 2 License

**Comment by michielb-prismtech** [comment]
The error message you're getting has todo with the OSPL_HOME environment variable which has not been set.
When you run our configure script make sure you source it
>$ source configure
