### ISSUE TITLE
Supporting forward slashes in topic names

### ISSUE THREAD

**Issue by dhood** [ADLINK-IST/opensplice#46]
Since there is an upcoming DDS spec that will allow forward slashes in topic names, ROS 2 is planning to move away from using {partition + topic} for our "namespacing" concept (see https://github.com/ros2/rmw_opensplice/pull/176) and use just topic names without partitions instead.

The other vendors we support for ROS 2 (Connext, FastRTPS) currently allow forward slashes in topic names: are you open to allowing slashes in OpenSplice in advance of the new spec?

**Comment by michielb-prismtech** [comment]
There is a proposal for a change of supported characters in topic names:
http://issues.omg.org/issues/lists/dds-rtf5#issue-42236
This issue has not yet been discussed and it is therefor not a given that the proposed characters will indeed be added.

I'll start an investigation into the forward slash to see if we can add this to our product, will get back to you on this.

**Comment by dhood** [comment]
Thanks for clarifying that it's not certain yet, and for looking into it.

**Comment by dirk-thomas** [comment]
> I'll start an investigation into the forward slash to see if we can add this to our product, will get back to you on this.

@michielb-prismtech Any news on this?

**Comment by michielb-prismtech** [comment]
@dirk-thomas I've ran into an issue with one of our services working on a solution

**Comment by dirk-thomas** [comment]
@michielb-prismtech Any update on this?

**Comment by michielb-prismtech** [comment]
@dirk-thomas sorry forgot to mention on this ticket, '/' support is in the master branch

**Comment by dirk-thomas** [comment]
> '/' support is in the master branch

That is great news - thank you.

For Linux we can re-roll our own Debian package with that change. How about the installers for macOS and Windows. Can you somehow provide us with an updated version of those (which should be also publically downloadable for ROS users)?

**Comment by michielb-prismtech** [comment]
Sorry missed the previous mail notifcation.
I can create a set of new installers, do you want me to cherry-pick the metaconfig.xml rename to ospl_metaconfig.xml in this installer as well?

**Comment by dirk-thomas** [comment]
We have built the new Debian package from the latest commit of the master branch. For consistency I would say it makes sense to use the same across all platforms.

I would rather not pick additional changes from future versions. While the name of the config isn't great atm it seems to work fine.

**Comment by michielb-prismtech** [comment]
Available in [OSPL_V6_7_180404OSS_RELEASE](https://github.com/ADLINK-IST/opensplice/releases/tag/OSPL_V6_7_180404OSS_RELEASE)

**Comment by dirk-thomas** [comment]
> A related question: the next ROS 2 release in June - Bouncy - will target Ubuntu 18.04 as well as Visual Studio 2017. Do you think it would be feasible to provide binaries for those by that time?

@michielb-adlink Friendly ping.

**Comment by michielb-adlink** [comment]
@dirk-thomas some testing indicates that it should be possible to compile OpenSplice with some minor changes on both Ubuntu 18.04 and Visual Studio 2017. Waiting for approval for new build systems

**Comment by dirk-thomas** [comment]
@michielb-adlink Any update on this?

**Comment by michielb-adlink** [comment]
@dirk-thomas 
Almost done, had a setback with vs2017
Just pushed the ubuntu1804 support (only buildsystem changes)

**Comment by dirk-thomas** [comment]
@michielb-adlink Do you have a timeline for the VS2017 binaries? Or do you expect that the VS2015 ones will be just fine?

**Comment by michielb-adlink** [comment]
@dirk-thomas available now

**Comment by dirk-thomas** [comment]
Thanks, I deployed the Visual Studio 2017 binaries on our executors.
