### ISSUE TITLE
Shiroryu

### ISSUE THREAD

**Issue by shiroryu** [ADLINK-IST/opensplice#47]
Hello, has anyone managed to use OpenSplice from a .Net Core 2.0 C# client ?

We have some issues with the HelloWorld sample on Windows (which works fine with the .Net Framework) : https://stackoverflow.com/questions/48993264/troubles-to-run-dds-opensplice-with-net-core

Regards

**Comment by ernstvanveenendaal** [comment]
You're correct that out-of-the-box, OpenSplice isn't useable with .NET Core 2.0, as we do not yet officially support this. 

However, a work-around is to remove the reference to the dcpssacsAssembly and replace it with a reference to different library. 
This library isn't included in the installation version but can be obtained from the source tree when the project is build. it is located at {OPENSPLICE_HOME}src\api\dcps\sacs\bld\x86_64.win64-dev\dcpssacs.dll.

Regards

**Comment by shiroryu** [comment]
Hello,

Thank you for this answer.

Now I am using Vortex OpenSplice and I could not find dcpssacs.dll (I only found only dcpssacAssembly.dll).

How can I build this dll ?

Thanks for your help,

Regards,
Nicolas Farcet

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : ernstvanveenendaal <notifications@github.com>
Envoyé : Wednesday, April 4, 2018 10:07:09 AM
À : ADLINK-IST/opensplice
Cc : shiroryu; Author
Objet : Re: [ADLINK-IST/opensplice] Shiroryu (#47)


You're correct that out-of-the-box, OpenSplice isn't useable with .NET Core 2.0, as we do not yet officially support this.

However, a work-around is to remove the reference to the dcpssacsAssembly and replace it with a reference to different library.
This library isn't included in the installation version but can be obtained from the source tree when the project is build. it is located at {OPENSPLICE_HOME}src\api\dcps\sacs\bld\x86_64.win64-dev\dcpssacs.dll.

Regards

**Comment by ernstvanveenendaal** [comment]
Hi Nicolas,

As the opensource version is closely related to the commercial version you're now using, this DLL isn't included as well in the commercial version. It is possible to build it yourself as all source code is included in the commercial version, however it might be better to raise a support ticket on the commercial version to add this DLL to the distribution, so that you will be notified that is has been solved. 

.NET core still isn't officially supported, as we aren't running any tests with it.

Regards,
Ernst

**Comment by shiroryu** [comment]
Hi Ernst,

Thank you for the feedback,

Regards,
Nicolas.

Provenance : Courrier<https://go.microsoft.com/fwlink/?LinkId=550986> pour Windows 10

________________________________
De : ernstvanveenendaal <notifications@github.com>
Envoyé : Thursday, June 14, 2018 9:52:41 AM
À : ADLINK-IST/opensplice
Cc : shiroryu; Author
Objet : Re: [ADLINK-IST/opensplice] Shiroryu (#47)


Hi Nicolas,

As the opensource version is closely related to the commercial version you're now using, this DLL isn't included as well in the commercial version. It is possible to build it yourself as all source code is included in the commercial version, however it might be better to raise a support ticket on the commercial version to add this DLL to the distribution, so that you will be notified that is has been solved.

.NET core still isn't officially supported, as we aren't running any tests with it.

Regards,
Ernst
