### ISSUE TITLE
Assert 'header->confidence == (0x504F5448)' if QosProvider is garbage collected

### ISSUE THREAD

**Issue by Gasper** [ADLINK-IST/opensplice#52]
Whenever QosProvider object is garbage collected program terminates with
> /{path}/src/database/database/code/c_base.c:2407: c_free: Assertion `header->confidence == (0x504F5448)' failed.

The issue occurs on OSPL_V6_7_180404OSS_RELEASE release (built from source) on Centos 7.3, Java 1.8 update 144.

Backtrace of the issue:
> #0  0x00007f874c5dd1f7 in raise () from /lib64/libc.so.6
> #1  0x00007f874c5de8e8 in abort () from /lib64/libc.so.6
> #2  0x00007f874c5d6266 in __assert_fail_base () from /lib64/libc.so.6
> #3  0x00007f874c5d6312 in __assert_fail () from /lib64/libc.so.6
> #4  0x00007f86f4e688d0 in c_free (object=0x7f87448d45b0) at /{...}src/database/database/code/c_base.c:2407
> #5  0x00007f86f4eb462c in sd_cdrInfoFree (ci=0x7f87448d9fd0) at /{...}src/database/serialization/code/sd_cdr.c:4435
> #6  0x00007f86f52a9ae9 in saj_copyCacheFree (copyCache=0x7f87448d65b0) at /{...}src/api/dcps/java/common/c/code/saj_copyCache.c:382
> #7  0x00007f86f52fbc92 in saj_qosProviderDeinitCopyCaches (_this=0x7f87448d7b50) at /{...}src/api/dcps/java/common/c/code/saj_qosProvider.c:136
> #8  0x00007f86f52fbf2f in Java_DDS_QosProvider_jniQosProviderFree (env=0x7f87440849f8, jqosProvider=0x7f8730cd8720, qosProvider=140218947435344)
>     at /{...}src/api/dcps/java/common/c/code/saj_qosProvider.c:234
> #9  0x00007f8735017a34 in ?? ()
> #10 0x00007f8730cd86f0 in ?? ()
> ...

The issue can be replicated with:
```
System.setProperty(ServiceEnvironment.IMPLEMENTATION_CLASS_NAME_PROPERTY,
		"org.opensplice.dds.core.OsplServiceEnvironment");
		
ServiceEnvironment env = ServiceEnvironment.createInstance(QosProviderTest.class.getClassLoader());
QosProvider provider = env.getSPI()
		.newQosProvider("file://path/to/qos.xml", "");

// Arbitrary call to prevent it from being removed as some optimization
provider.toString();

// Set it to null and wait for it to be garbage collected
provider = null;
System.gc();

List<Object> objects = new LinkedList<>();
for (int i = 0; i < 20000000; i++) {
	objects.add(new Object());
}
```

**Comment by michielb-adlink** [comment]
Issue fixed by cherry-pick of aff411ea6c1714afbf5e2908e9d02d32fa7e8147
