### ISSUE TITLE
Segfault: disabling builtin-topics

### ISSUE THREAD

**Issue by PRADEEPKJ** [ADLINK-IST/opensplice#55]
Hi All,

I tried to disable the builtin-topics while creating the pubs and subs.
Followed below way to disable

<Domain>
   <BuiltinTopics enabled="false"/>
</Domain>
But I am facing the segfault issue

v_dataReaderFree (_this=0xffffa80021a0) at /home/.../ospl/src/kernel/code/v_dataReader.c:791
791         if (v_reader(_this)->qos->share.v.enable) {

Please let me know how can I disable the builtin topics.

Thanks & Regards,
Pradeep

**Comment by michielb-adlink** [comment]
@PRADEEPKJ which way did you follow to disable the builtin-topics?

**Comment by PRADEEPKJ** [comment]
Used xml configs to disable.

-Pradeep

**Comment by michielb-adlink** [comment]
@PRADEEPKJ That is the correct way. I'm able to reproduce the issue you're running into I'll investigate.
