### ISSUE TITLE
Core dumped in Listener example

### ISSUE THREAD

**Issue by aim2nasa** [ADLINK-IST/opensplice#57]
- From the DCPS Listener example
On the way testing Listener function of DDS, I encountered the following errors which seemed to be raised from the core.
```
rossi@retriever:~/opensplice/install/HDE/x86_64.linux-dev/examples/dcps/Listener/cpp/standalone$ ./sacpp_listener_sub 
=== [ListenerDataSubscriber] set_listener
=== [ListenerDataSubscriber] Ready ...
sacpp_listener_sub: /home/rossi/opensplice/src/kernel/code/v_status.c:514: v_statusReset: Assertion `s != NULL' failed.
Aborted (core dumped)
rossi@retriever:~/opensplice/install/HDE/x86_64.linux-dev/examples/dcps/Listener/cpp/standalone$ 

```
- Similar error was also found in the example for this as well.
https://github.com/ADLINK-IST/dds-tutorial-cpp-ex/blob/master/ch3/ltssub.cpp
```
rossi@retriever:~/dds-tutorial-cpp-ex/ch3$ ./ltssub 
ltssub: /home/rossi/opensplice/src/kernel/code/v_status.c:514: v_statusReset: Assertion `s != NULL' failed.
Aborted (core dumped)
rossi@retriever:~/dds-tutorial-cpp-ex/ch3$ 

```

**Comment by michielb-adlink** [comment]
I'm unable to reproduce the issue, could you provide us with a stack trace?

**Comment by kjrusscher** [comment]
I'm running into the same problem with isocpp2 now, both with my own code as well as the OpenSplice examples. @aim2nasa Did you manage to solve this problem? If so, what caused the problem?
