### ISSUE TITLE
Issue installing community opensplice on Mac High Sierra 10.13.3

### ISSUE THREAD

**Issue by ngunhaSO** [ADLINK-IST/opensplice#60]
Any workaround for installing on Mac without disabling the SIP? I follow the instruction here http://www.prismtech.com/dds-community/building but I am stuck at the make stage.

**source configure**
Setup at 11:01:35 for Vortex - Version 6.7.180404OSS - Date 2018-07-26

MAKE: OK - using GNU Make 3.81
Perl: OK - using perl version='5.18.2';
Qt: Disabled. OSPL_QT_IS_ON was: no
GAWK: OK - using GNU Awk 4.2.1, API: 2.0 (GNU MPFR 4.0.1, GNU MP 6.1.2)
BISON: OK - using bison (GNU Bison) 2.3
FLEX: OK - using 2.5.35
JAVAC: Warning - you should set JAVA_COMPATJAR to rt.jar for Java 1.6
OK - using JAVAC version 1.8.0_152
   JAVA_HOME is /Library/Java/Home
GMCS: Warning - No gmcs compiler found
   gmcs C# compiler not found, disabling SACS api build.
TAO: Warning - No TAO found
   TAO environment not set, disabling TAO related features.
JACORB: Warning - JACORB_HOME not set
   JACORB environment not set, disabling JACORB related features.
GSOAP: OK - using GSOAP version 2.8.69
  setting GSOAPHOME to /usr/local/Cellar/gsoap/2.8.69
DOXYGEN: Warning - ospl_docs repo cannot be reached and doxygen not installed
  Generated documentation will not be available
GOOGLE PROTOCOL BUFFERS: PROTOBUF_HOME has not been set
Warning - Protobuf compiler environment not set, building of all protobuf related features is disabled.
C99: OK - supported
Configuration OK

**make && make install**
dyld: Library not loaded: @rpath/libddshts.dylib
  Referenced from: /HDE/x86_64.darwin10_clang/src/VortexOpenSplice/exec/x86_64.darwin10_clang-release/idlpp
  Reason: image not found

UPDATED: 
So, after I disabled the SIP, I reran the make && make install. Then I got another error:
DEP soapServer.c
DEP soapC.c
DEP ../../code/cmsoap.c
DEP ../../code/cms_thread.c
DEP ../../code/cms_soapThread.c
DEP ../../code/cms_soap2.c
DEP ../../code/cms_service.c
DEP ../../code/cms_configuration.c
DEP ../../code/cms_client.c
make[4]: *** No rule to make target `stdsoap2.d', needed by `link'.  Stop.
make[3]: *** [link] Error 2
make[2]: *** [cmsoap.ss_link] Error 2
make[1]: *** [services.ss_link] Error 2
make: *** [src.ss_link] Error 2

**Comment by michielb-adlink** [comment]
Looking into the SIP problem

Other build issue can be solved by not setting GSOAP_HOME before running configure of by copying the stdsoap.c file to GSOAP_HOME/include

**Comment by michielb-adlink** [comment]
The SIP issue is fixed in the master branch already by the commit with id OSPL-10866

**Comment by votecoffee** [comment]
I had the same issue on windows 10/VS 2019 and copying the stdsoap.c file to GSOAP_HOME/include worked for me.  I also jury rigged it for VS2019/Windows 10 SDK changes by modifying C:\opensplice\setup\x86_64.win64-default.mak

Fix VS2015 section to match below:
# VS2015
   VS_INCLUDE =  -I"$(VS_HOME)/VC/include"
   VS_INCLUDE += -I"$(VS_HOME)/VC/Tools/MSVC/14.29.30037/include"
   VS_INCLUDE += -I"$(WINDOWSSDKDIR)/Include/10.0.19041.0/ucrt"
   VS_INCLUDE += -I"$(WINDOWSSDKDIR)/Include/10.0.19041.0/um"
   VS_INCLUDE += -I"$(WINDOWSSDKDIR)/Include/10.0.19041.0/shared"
   VS_INCLUDE += -I"$(WINDOWSSDKDIR)/../8.1/Include/um"
   VS_INCLUDE += -I"$(WINDOWSSDKDIR)/../8.1/Include/shared"
   
   VS_LIB_FLAGS =  -L"$(VS_HOME)/VC/lib/amd64"
   VS_LIB_FLAGS += -L"$(VS_HOME)/VC/Tools/MSVC/14.29.30037/lib/x64"
   VS_LIB_FLAGS += -L"$(WINDOWSSDKDIR)/Lib/10.0.19041.0/ucrt/x64"
   VS_LIB_FLAGS += -L"$(WINDOWSSDKDIR)/Lib/10.0.19041.0/um/x64"
   VS_LIB_FLAGS += -L"$(WINDOWSSDKDIR)/../8.1/Lib/winv6.3/um/x64"
   VS_LIB_FLAGS += -L"$(WINDOWSSDKDIR)/../8.1/lib/x64"
endif
