### ISSUE TITLE
get BuiltinTopicKey_t key

### ISSUE THREAD

**Issue by reed-lau** [ADLINK-IST/opensplice#63]
how can get the global unique uuid from one handle ( InstanceHandle_t)

i found some metho using v_gid and translator, but the .seial is specified 0, but the key[3] is not 0 sometimes, can I assign it mannually. 

thanks much.

**Comment by michielb-adlink** [comment]
I believe this is answered here:
https://github.com/ros2/rosidl_typesupport_opensplice/issues/4
