### ISSUE TITLE
Register datareader instance

### ISSUE THREAD

**Issue by gdelhomme** [ADLINK-IST/opensplice#64]
In order to reduce memory allocation during runtime and knowing the structure of the topic, I would like to avoid any memory allocation during applications run.
For this purpose and similar to datawriter, is it possible to register a datareader instance before a first sample has been received ?
Is there any other way to avoid memory allocation during runtime ? (shared memory init size for example ?)
Thanks,

**Comment by michielb-adlink** [comment]
In the our opensource project this is not possible.
In our commercial version we have shared memory deployment mode. You can find information about this in the [Deployment Guide](https://github.com/ADLINK-IST/opensplice/blob/master/docs/pdf/OpenSplice_DeploymentGuide.pdf). Is this what you are looking for?
If not what problem are you trying to solve?
