### ISSUE TITLE
xtypes/TypeKind.hpp type typo in isocpp interfaces

### ISSUE THREAD

**Issue by joakimono** [ADLINK-IST/opensplice#70]
When trying to use the xtypes interface of isocpp or isocpp2 we get an compilation error.
`enum type` should be `enum Type` in the TypeKind_def struct of both isocpp and isocpp2:
* opensplice/src/api/dcps/isocpp/include/spec/dds/core/xtypes/TypeKind.hpp
* opensplice/src/api/dcps/isocpp2/include/dds/core/xtypes/TypeKind.hpp

As an example the dds::core::safe_enum in SafeEnumeration.hpp expects the second template type to be `def::Type` with a capital T, not `def::type`.

We are currently patching this with the following command:
`sed -i 's|enum type|enum Type|' src/api/dcps/{isocpp/include/spec,isocpp2/include}/dds/core/xtypes/TypeKind.hpp`

**Comment by hansvanthag** [comment]
Xtypes isn't supported in OpenSplice, however we do support Google-protocol-buffers which also offers an extensible data-model (and is widely known/recognized)

**Comment by michielb-adlink** [comment]
Fixed by 339f1015cba2cef839b56cbdca64ab2308f81f08
