### ISSUE TITLE
Durability service problems

### ISSUE THREAD

**Issue by WOLFY888** [ADLINK-IST/opensplice#71]
I'm trying to understand the work of the durability service and some features of his work I do not understand:
- according to the OMG version 1.4 standard, the data writer must have durability_service qos policy, but in the OpenSplice implementation of version 6.9, the data writer does not have such a qos policy;
- unable to deliver data to the data reader who joined after the original data writer wrote the data and completed the work. At this time, the durability service is configured by default. Maybe to solve this problem I should explicitly write some settings in the configuration file?
- the StoreSessionTime element in the configuration file, as far as I understand, determines the time at the end of which the data received by the reader is written to the file (StoreDirectory path). But in reality, the reader writes the data to the file immediately after it has been accepted, and after the Store Session Time(default 20 seconds) deletes the data from the file. Do I misunderstand the functionality of this item?

**Comment by kortstee** [comment]
@WOLFY888 The DurabilityServiceQosPolicy is meant to drive the durability behaviour for a specific Topic and that makes sense in a data-centric world like DDS where there's basically one global data space. Therefore it does not make sense to set it per DataWriter as well. How would the DDS implementation have to deal with different DurabilityQosPolicy settings for a given Topic, right? The availability of this policy on the DataWriter is therefore deemed an omission in the DDS standard. There is already two open issues in the OMG DDS Revision Task Force; https://issues.omg.org/issues/lists/dds-rtf5#issue-13958 and https://issues.omg.org/issues/lists/dds-rtf5#issue-14092 that propose to remove that policy from the DataWriter. As it would not be possible to implement unambiguous semantics with this policy on DataWriter-level, OpenSplice does not provide them there. Makes sense?

**Comment by kortstee** [comment]
With respect to the removal of data from permanent storage; have you by any chance been using the default values for the WriterDataLifecycleQos.autodispose_unregistered_instances on your DataWriter? If you delete your DataWriter, all written instances are automatically unregistered. If the value of this policy is set to TRUE (default value), all instances are disposed as well. As a result, your data gets removed from persistent and/or transient storage as well. If this is indeed your scenario, changing the value of the policy to FALSE should do the trick.

**Comment by WOLFY888** [comment]
@kortstee Yes, thanks, the problem with deleting the received data from the file was solved. But how to fix the problem that a later-connected reader still doesn't get the data written by the writer before the reader joins?

**Comment by kortstee** [comment]
Can you please share the full set of QoS settings of your Topic, DataWriter and DataReader?

**Comment by WOLFY888** [comment]
@kortstee 
![reader_qos](https://user-images.githubusercontent.com/44889553/48257747-6f2d5e80-e424-11e8-98fb-faf6d7eeac9c.jpg)
![topic_qos](https://user-images.githubusercontent.com/44889553/48257749-6f2d5e80-e424-11e8-9c4f-78c1f97a59e5.jpg)
![writer_qos](https://user-images.githubusercontent.com/44889553/48257750-6fc5f500-e424-11e8-8cc7-36101eafa30f.jpg)

**Comment by kortstee** [comment]
Your QoS settings seem correct. You may need to wait for this historical data to come in after you've created your DataReader. It is possible to synchronise on that delivery process completing before you starting reading by means of the wait_for_historical_data() operation on the DataReader. This operation will block until delivery has completed (or has timed out depending on your time-out parameter). If you put that in before you start reading, does it work?

**Comment by WOLFY888** [comment]
@kortstee The application calls wait_for_historical_data() and without him is no different. In both cases, the data reader receives the same data - the data that is available in the storage file(pstore) at the time of reading. So I have a question - should data written by the data writer immediately saved in that file for further reading connected later by the data reader?  In my case, includes only the data that is read by the data reader in real time directly from the data writer. In other words, if there is only a writer and he writes data in the absence of the reader, then this data is lost and does not get into the file. Can this indicate incorrect operation or incorrect configuration of the durability service? I attach the contents of the ospl.xml, maybe you will see some problems in it.
![ospl](https://user-images.githubusercontent.com/44889553/48298481-457d4180-e4cf-11e8-9db8-cd8510a439cc.jpg)

**Comment by WOLFY888** [comment]
@kortstee The cause of the problem is found! The writer finished his work too early and the data recorded by him simply did not have time to be saved to a file. This is due to the fact that the writer finished the work before the time specified in the item Store Session Time. Empirically, it was found that this element has a minimum value of about 6 seconds. If you set the time in the configuration file to less than 6 seconds, the data will still be written to the storage not earlier than 6 seconds. This is a feature of the service or the time depends on other factors, such as CPU load, etc?
