### ISSUE TITLE
QosProvider missing calls in isocpp2

### ISSUE THREAD

**Issue by HarryDC** [ADLINK-IST/opensplice#72]
The isocpp2 definition of QOSProvider is missing the call to get to the qos without providing the id. The whole suite is missing, `participant_qos()`, `topic_qos()`, `subscriber_qos()`, etc. The parameter-less calls are present in the documentation. 

All the calls taking a string parameter are present.

**Comment by ThijsSassen** [comment]
@HarryDC  when the call is done without an argument the parameter call with argument NULL is used. This defaults to the default QoS profile, for more details see [this file](https://github.com/ADLINK-IST/opensplice/blob/master/src/api/dcps/isocpp2/include/dds/core/detail/TQosProviderImpl.hpp)

**Comment by HarryDC** [comment]
That might be but that is not working for me for example the following call `subscriberQos = provider->subscriber_qos();` prduces a compiler error under Visual Studio 2017

```
1>Subscriber.cpp
1>d:\simquest\msta-source\msta\runtime\subscriberprivate.h(48): error C2660: 'org::opensplice::core::QosProviderDelegate::subscriber_qos': function does not take 0 arguments
1>d:\tools\cygwin\home\hscheirich\opensplice-build\opensplice-git\install\hde\x86_64.win64\include\dcps\c++\isocpp2\org\opensplice\core\qosproviderdelegate.hpp(67): note: see declaration of 'org::opensplice::core::QosProviderDelegate::subscriber_qos'
1>d:\simquest\msta-source\msta\runtime\subscriberprivate.h(22): note: while compiling class template member function 
...
```
A call with a string parameter gets resolved correctly. I tried including `dds/dds.hpp` `dds/core/QosProvider.hpp` wit the same result

**Comment by HarryDC** [comment]
@ThijsSassen Looking at the documentation here : http://download.prismtech.com/docs/Vortex/apis/ospl/isocpp2/html/a00211.html

The following snippet doesn't compile, it seems that it should ...

``` 
#include <dds/dds.hpp>

void main()
{
	dds::core::QosProvider provider("file://");

	provider->subscriber_qos();
}
```

Btw the file that is being references in the error is : 
https://github.com/ADLINK-IST/opensplice/blob/master/src/api/dcps/isocpp2/include/org/opensplice/core/QosProviderDelegate.hpp

which is different from the one that you pointed to

**Comment by ThijsSassen** [comment]
@HarryDC can you try this:

```
#include <dds/dds.hpp>

void main()
{
	dds::core::QosProvider provider("file://");

	provider.subscriber_qos();
}
```
notice the . in stead of -> with the -> you get the internal delegate object which does not have the function in stead of the api object which does have it.

**Comment by HarryDC** [comment]
@ThijsSassen ouch, yea that works ... i need to be more careful with that, thanks !
