### ISSUE TITLE
Visual Studio 2019 installer

### ISSUE THREAD

**Issue by dirk-thomas** [ADLINK-IST/opensplice#86]
Provide a Visual Studio 2019 installer for the latest release.

**Comment by ThijsSassen** [comment]
@dirk-thomas I updated the repository to support vs 2019 you can now build OpenSplice with visual studio 2019. I didn't have time to create installers so if you want them you can create them yourself now.

**Comment by dirk-thomas** [comment]
> I didn't have time to create installers so if you want them you can create them yourself now.

I am sorry but I won't have time for that either. Please comment on this ticket once they are available I will deploy the VS2019 version of OpenSplice to our CI nodes.

**Comment by ThijsSassen** [comment]
@dirk-thomas i added the VS 2019 build you can download it [here](https://github.com/ADLINK-IST/opensplice/releases/download/OSPL_V6_9_190624OSS_RELEASE/PXXX-VortexOpenSplice-6.9.190624OSS-HDE-x86_64.win-vs2019-installer.zip)
