### ISSUE TITLE
Using DDSI2E

### ISSUE THREAD

**Issue by eelcocramer** [ADLINK-IST/opensplice#89]
Hi,

I'm trying to configure and use the DDSI2E networking service but I keep getting the exception:

```
Exception in thread "main" org.omg.dds.core.DDSException: Unable to connect to domain id = <ANY>.
        The most common causes of this error are an incorrect configuration file or 
        that OpenSpliceDDS is not running (when using shared memory mode). at u_participantNew (u_participant.c:234)
```

I'm not using the shared memory mode. Is there an example configuration for the DDSI2E networking service? Or does it only work in the shared memory mode?

**Comment by eelcocramer** [comment]
The error was probably because of a configuration error. Is DDSI2E supported in the community edition?

**Comment by ThijsSassen** [comment]
@eelcocramer no DDSI2E is a commercial service, the community edition only support DDS2.

**Comment by eelcocramer** [comment]
Thanks @ThijsSassen. FYI it seems that I can make a working configuration with DDSI2E. Also the .so file for DDSI2E is present in the community edition download.

**Comment by ThijsSassen** [comment]
@eelcocramer yes you are correct DDSI2E used to be commercial but its now also available in the community.

**Comment by eelcocramer** [comment]
Ok, than it makes sense that I can use it.

Whenever I add `<Channels>` I will get the exception. Without configuring channels everything works fine.
