### ISSUE TITLE
No darwin binaries for OSPL_V6_9_190705OSS

### ISSUE THREAD

**Issue by wjwwood** [ADLINK-IST/opensplice#97]
There is no darwin binary here:

https://github.com/ADLINK-IST/opensplice/releases/tag/OSPL_V6_9_190705OSS_RELEASE

but there is one for previous releases, e.g.:

https://github.com/ADLINK-IST/opensplice/releases/tag/OSPL_V6_9_190403OSS_RELEASE

Would it be possible to get darwin binaries for this release?

**Comment by dirk-thomas** [comment]
@MarcelJordense FYI

**Comment by MarcelJordense** [comment]
Darwin binaries have been added now for OSPL_V6_9_190705OSS_RELEASE

**Comment by wjwwood** [comment]
Thanks!
